### ISSUE TITLE
New sites not listed when using ploi init

### ISSUE THREAD

**Issue by robdekort** [schmidfelix/ploi-cli#4] opened 2021-02-27 09:17 UTC
Hi Felix,

I love the CLI, thank you for making this! Since initialising the CLI tool it seems new sites aren't being loaded when I init a project. I just see the sites that were available when I started using the CLI.

I can however link a project by manually creating the ploi.yml file.

**Comment by schmidfelix** [comment] 2021-02-27 14:46
Hi, first of all thanks for the kind words.

Could you explain where you would expect your sites to be shown or how to reproduce that?

Do you mean when running `ploi init`, selecting a server and then trying to link the repository to an already existing site?

**Comment by robdekort** [comment] 2021-02-27 19:46
Hi Felix, yes I’m sorry. That’s exactly what I mean. Let me know if you need to know more. :-)

**Comment by schmidfelix** [comment] 2021-03-02 07:16
That's kind of weird. The tool sends an API request every time you select "No" after asking you to create a new site https://github.com/schmidfelix/ploi-cli/blob/473bf444950a2918fda0e50d4046337cf2d9c3da/app/Commands/InitCommand.php#L61 and does not do any caching. 

Please make sure to also select the correct server before. Are your sites listed in the ploi.io dashboard on the selected server?

**Comment by robdekort** [comment] 2021-03-02 07:53
That's weird indeed. My site is listed on the dashboard. Feel free to reach out on Discord if you want me to send some screenshots of both listings. You're probably active there as well :-).

**Comment by schmidfelix** [comment] 2021-03-10 14:17
As the tool doesn't do any caching and I can't reproduce that by myself, as well as no other have complained about that I'm going to close the issue. 

I've just messaged you on Discord, if we find a solution I'm going to add that to the issue when someone else runs into that problem.

**Closed as completed by schmidfelix** 2021-03-10 14:17 UTC
